export interface LyricLine {
  id: number;
  text: string;
  chorus?: boolean;
  bridge?: boolean;
}

export const lyrics: LyricLine[] = [
  { id: 1, text: "Shake ya ass, watch yourself", chorus: true },
  { id: 2, text: "Shake ya ass, show me what you workin' with", chorus: true },
  { id: 3, text: "Shake ya ass, watch yourself", chorus: true },
  { id: 4, text: "Shake ya ass", chorus: true },
  { id: 5, text: "I came here with my dick in my hand", chorus: false },
  { id: 6, text: "Don't make me leave here with my foot in yo ass; be cool", chorus: false },
  { id: 7, text: "And don't worry bout how I'm rippin this shit", chorus: false },
  { id: 8, text: "When I'm flipping what I'm kicking ____, that's just what I do", chorus: false },
  { id: 9, text: "I'm effervescent and I'm off that crescent", chorus: false },
  { id: 10, text: "Nastier than a full grown German Shepherd; motherfucker keep stepping", chorus: false },
  { id: 11, text: "They don't fuck with me and they don't", chorus: false },
  { id: 12, text: "Y'all bitches can't catch me and you won't", chorus: false },
  { id: 13, text: "Pay ya fare, fix your hair, throw that pussy", chorus: false },
  { id: 14, text: "Got a Prada for bonapalies, and Donna for my babooski", chorus: false },
  { id: 15, text: "You think I'm tricking? Bitch, I ain't trippin", chorus: false },
  { id: 16, text: "I'm buyin if you got nice curves for your iceberg", chorus: false },
  { id: 17, text: "Drinkin Henn and acting like it do something to me", chorus: false },
  { id: 18, text: "Hope this indecent proposal make you do somethin with me", chorus: false },
  { id: 19, text: "Fuck a dollar girl, pick up fifty", chorus: false },
  { id: 20, text: "And fuck that coward, girl, you need a real ____", chorus: false },
  { id: 21, text: "Off top knick-a-boxers hurting shit", chorus: false },
  { id: 22, text: "Bend over ho; show me what you workin with!", chorus: false },
  { id: 23, text: "Shake ya ass, watch yourself", chorus: true },
  { id: 24, text: "Shake ya ass, show me what you working with", chorus: true },
  { id: 25, text: "Shake ya ass", chorus: true },
  { id: 26, text: "Shake ya ass", chorus: false },
  { id: 27, text: "Attention all y'all players and pimps", bridge: true },
  { id: 28, text: "Right now in the place to be (shake ya ass)", bridge: true },
  { id: 29, text: "I thought I told y'all ____ before", bridge: true },
  { id: 30, text: "Y'all ____ can't fuck with me (watch yourself)", bridge: true },
  { id: 31, text: "Now this ain't for no small booties", bridge: true },
  { id: 32, text: "No sir cause that won't pass (show me whatcha workin with)", bridge: true },
  { id: 33, text: "But if you feel you got the biggest one", bridge: true },
  { id: 34, text: "Then momma come shake ya ass", bridge: true },
  { id: 35, text: "Shake ya ass, watch yourself", chorus: true },
  { id: 36, text: "Shake ya ass, show me what you working with", chorus: true },
  { id: 37, text: "Shake ya ass, watch yourself", chorus: true },
  { id: 38, text: "Shake ya ass, show me what you working with", chorus: true },
  { id: 39, text: "I like my women fire like CAY-ENNE!!" },
  { id: 40, text: "Chocolate and bowlegged - when I'm runnin up behind her!!" },
  { id: 41, text: "Go head do your job, pop the lock, let the cock out" },
  { id: 42, text: "For real though girl don't lie you know you wanna go back to my house" },
  { id: 43, text: "\"The Man Right Chea\" wanna get under that dress right there" },
  { id: 44, text: "You spicy cajun we gon' pass a good time over there" },
  { id: 45, text: "You better suck the head on them there crawfish" },
  { id: 46, text: "And you gotta bend all the way over to dance off this" },
  { id: 47, text: "Handle yo' business but I know you do it way better, you dead wrong" },
  { id: 48, text: "So if you talking bout how ____ make noise when you pass by" },
  { id: 49, text: "Get yo' fine ass on the floor girl this yo' fuckin song!" },
  { id: 50, text: "Do yo' thang dont be scurred" },
  { id: 51, text: "'Cause you gon' get served" },
  { id: 52, text: "Get mine then you gon' get churs" },
  { id: 53, text: "Bout to make yo' ass love it" },
  { id: 54, text: "Raise it up, show the G-string hustling hustling" },
  { id: 55, text: "Attention all y'all players and pimps", bridge: true },
  { id: 56, text: "Right now in the place to be (shake ya ass)", bridge: true },
  { id: 57, text: "I thought I told y'all ____ before", bridge: true },
  { id: 58, text: "Y'all ___ can't fuck with me (watch yourself)", bridge: true },
  { id: 59, text: "Now this ain't for no small booties", bridge: true },
  { id: 60, text: "No sir cause that won't pass (show me whatcha workin with)", bridge: true },
  { id: 61, text: "But if you feel you got the biggest one", bridge: true },
  { id: 62, text: "Then momma come shake ya ass", bridge: true },
  { id: 63, text: "Shake ya ass, watch yourself", chorus: true },
  { id: 64, text: "Shake ya ass, show me what you working with", chorus: true },
  { id: 65, text: "Shake ya ass, watch yourself", chorus: true },
  { id: 66, text: "Shake ya ass, show me what you working with", chorus: true },
  { id: 67, text: "Stop yo' cryin heffer, I don't need all that" },
  { id: 68, text: "I got a job for you - the braided up pimp is back" },
  { id: 69, text: "Break them handcuffs, fuck you ____ move something" },
  { id: 70, text: "And if they ask you what you doin say, \"Ooohh nuttin!\"" },
  { id: 71, text: "And we been doin for the past 2 somethin" },
  { id: 72, text: "And I've been beatin that pussy up not smooth fucking" },
  { id: 73, text: "You can betcha bottom dollar; if that pussy fire" },
  { id: 74, text: "You gon' holla Michael Tyler!" },
  { id: 75, text: "So don't act like you don't be backin that stuff up" },
  { id: 76, text: "Girl in the club, cause that's what you got ass for" },
  { id: 77, text: "Wobble wobble I'm infatuated" },
  { id: 78, text: "Bitch ride a dick like she making a baby" },
  { id: 79, text: "And I see that we gon' have to go to a quiet corner for just us two an'" },
  { id: 80, text: "Don't worry about who looking, just keep on doing what you doing" },
  { id: 81, text: "Cause a ____ like me gon' get to work before I know the girl" },
  { id: 82, text: "Bitch what's happening, let 'em see, show the world!" },
  { id: 83, text: "Attention all y'all players and pimps", bridge: true },
  { id: 84, text: "Right now in the place to be (shake ya ass)", bridge: true },
  { id: 85, text: "I thought I told y'all ____ before", bridge: true },
  { id: 86, text: "Y'all ____ can't fuck with me (watch yourself)", bridge: true },
  { id: 87, text: "Now this ain't for no small booties", bridge: true },
  { id: 88, text: "No sir cause that won't pass (show me whatcha workin with)", bridge: true },
  { id: 89, text: "But if you feel you got the biggest one", bridge: true },
  { id: 90, text: "Then momma come shake ya ass", bridge: true },
  { id: 91, text: "Shake ya ass, watch yourself", chorus: true },
  { id: 92, text: "Shake ya ass, show me what you working with", chorus: true },
  { id: 93, text: "Shake ya ass, watch yourself", chorus: true },
  { id: 94, text: "Shake ya ass, show me what you working with", chorus: true },
  { id: 95, text: "Shake ya ass, watch yourself", chorus: true },
  { id: 96, text: "Shake ya ass, show me what you working with", chorus: true },
  { id: 97, text: "Shake ya ass, watch yourself", chorus: true },
  { id: 98, text: "Shake ya ass, show me what you working with", chorus: true },
  { id: 99, text: "Uhh.. OOOH-WEE! Good lawd!" },
  { id: 100, text: "Damn!" },
  // Add more lyrics as needed
]; 